name: hashd
description: Hash Code deamon to run the Hash code 2020 competition.
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  args: ^2.3.0
  async: ^2.8.2
  glob: ^2.0.2
  logger: ^1.1.0
