CC=cargo
FMT=fmt

OPTIONS=

default: fmt
	$(CC) build

fmt:
	$(CC) $(FMT) --all

# The run command need some work with the option passing.
run:
	@echo "Nothings yet"

build:
	$(CC) build --release

check:
	@echo "Nothings yet"
